/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHAT
 */
public class QUANTRI extends JFrame {

    /**
     * Creates new form ADMIN
     */
    private String user;
    private String maNV, maKH;
    DefaultTableModel dtm;
    int diem;
    Connection ketNoi = KNCSDL.layKetNoi();
    int k, l, dem;

    public QUANTRI(String user) {
        initComponents();
        dateChooserCombo1.setEnabled(false);
        jMenu_QuanLy.setVisible(false);
        this.user = user;
        this.maNV = layMaNV(user);
        if (kiemTraVaiTro(user)) {
            jMenu_QuanLy.setVisible(true);
        }
        loadComboBoxLoaiDV();
        JPanel pn1 = new JPanel();
        JPanel pn2 = new JPanel();
        pn1.add(pn2);
        btn_Back.setEnabled(false);
        rb_10.setEnabled(false);
        rb_25.setEnabled(false);
        rb_50.setEnabled(false);
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(215, 205, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private QUANTRI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnKhungTren = new javax.swing.JPanel();
        pnNhanVien = new javax.swing.JPanel();
        lbNhanVien = new javax.swing.JLabel();
        txt_NVDangNhap = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        pnKhachHang = new javax.swing.JPanel();
        pnVoucherGroup = new javax.swing.JPanel();
        pnGroupButton = new javax.swing.JPanel();
        rb_0 = new javax.swing.JRadioButton();
        rb_10 = new javax.swing.JRadioButton();
        rb_25 = new javax.swing.JRadioButton();
        rb_50 = new javax.swing.JRadioButton();
        lbVoucher = new javax.swing.JLabel();
        lbTongToen1 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbTongToen2 = new javax.swing.JLabel();
        txt_TongTienCK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbTongToen = new javax.swing.JLabel();
        txt_TongTienTT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pnThongTinKhach = new javax.swing.JPanel();
        lbSoDTKhachHang = new javax.swing.JLabel();
        txt_SoDTKH = new javax.swing.JTextField();
        lbTenKhachHang = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lbDiaChiKhachHang = new javax.swing.JLabel();
        txt_DiaChiKH = new javax.swing.JTextField();
        btn_ThemKH = new javax.swing.JButton();
        pnButtonChinh = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DichVu = new javax.swing.JTable();
        btHuyDH = new javax.swing.JButton();
        btXoaDV = new javax.swing.JButton();
        btThanhToan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_LoaiDV = new javax.swing.JComboBox<>();
        cb_DichVu = new javax.swing.JComboBox<>();
        btn_Next = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_GiamSL = new javax.swing.JButton();
        pnDichVu = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_QuanLy = new javax.swing.JMenu();
        jMenu_ThongTinNV = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ KHÁCH HÀNG");

        pnNhanVien.setBackground(new java.awt.Color(0, 102, 102));
        pnNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnNhanVien.setPreferredSize(new java.awt.Dimension(455, 35));

        lbNhanVien.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hi_48px.png"))); // NOI18N
        lbNhanVien.setText("Xin chào bạn, ");

        txt_NVDangNhap.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        txt_NVDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        txt_NVDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_NVDangNhap.setText("Tên nhân viên");

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NVDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_NVDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE))
        );

        dateChooserCombo1.setFormat(0);
        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 16));
        dateChooserCombo1.setLocale(new java.util.Locale("vi", "", ""));

        pnKhachHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnGroupButton.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup2.add(rb_0);
        rb_0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_0.setSelected(true);
        rb_0.setText("0%");
        rb_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_0ActionPerformed(evt);
            }
        });
        pnGroupButton.add(rb_0);

        buttonGroup2.add(rb_10);
        rb_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_10.setText("10%");
        rb_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_10ActionPerformed(evt);
            }
        });
        pnGroupButton.add(rb_10);

        buttonGroup2.add(rb_25);
        rb_25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_25.setText("25%");
        rb_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_25ActionPerformed(evt);
            }
        });
        pnGroupButton.add(rb_25);

        buttonGroup2.add(rb_50);
        rb_50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb_50.setText("50%");
        rb_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_50ActionPerformed(evt);
            }
        });
        pnGroupButton.add(rb_50);

        lbVoucher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVoucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVoucher.setText("Chiết khấu:");

        lbTongToen1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongToen1.setText("TỔNG TIỀN:");

        txt_TongTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_TongTien.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("VNĐ");

        lbTongToen2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongToen2.setText("TIỀN CHIẾT KHẤU:");

        txt_TongTienCK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_TongTienCK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_TongTienCK.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("VNĐ");

        lbTongToen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongToen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongToen.setText("TIỀN CẦN THANH TOÁN:");

        txt_TongTienTT.setEditable(false);
        txt_TongTienTT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_TongTienTT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_TongTienTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TongTienTTMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("VNĐ");

        javax.swing.GroupLayout pnVoucherGroupLayout = new javax.swing.GroupLayout(pnVoucherGroup);
        pnVoucherGroup.setLayout(pnVoucherGroupLayout);
        pnVoucherGroupLayout.setHorizontalGroup(
            pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                                .addComponent(lbTongToen2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TongTienCK, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTongToen1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(pnGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTongToen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnVoucherGroupLayout.setVerticalGroup(
            pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVoucherGroupLayout.createSequentialGroup()
                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongToen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongTienCK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongToen2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnVoucherGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongToen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnThongTinKhach.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbSoDTKhachHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbSoDTKhachHang.setText("Số Điện Thoại    :");

        txt_SoDTKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SoDTKHKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SoDTKHKeyTyped(evt);
            }
        });

        lbTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbTenKhachHang.setText("Tên Khách Hàng :");

        txt_TenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TenKHKeyTyped(evt);
            }
        });

        lbDiaChiKhachHang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbDiaChiKhachHang.setText("Địa Chỉ:");

        btn_ThemKH.setText("Thêm khách hàng mới");
        btn_ThemKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemKHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinKhachLayout = new javax.swing.GroupLayout(pnThongTinKhach);
        pnThongTinKhach.setLayout(pnThongTinKhachLayout);
        pnThongTinKhachLayout.setHorizontalGroup(
            pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKhachLayout.createSequentialGroup()
                .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKhachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenKhachHang)
                            .addComponent(lbSoDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKhachLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDiaChiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_SoDTKH, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(txt_TenKH)
                    .addComponent(txt_DiaChiKH))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKhachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ThemKH)
                .addGap(103, 103, 103))
        );
        pnThongTinKhachLayout.setVerticalGroup(
            pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKhachLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SoDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoDTKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDiaChiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnButtonChinhLayout = new javax.swing.GroupLayout(pnButtonChinh);
        pnButtonChinh.setLayout(pnButtonChinhLayout);
        pnButtonChinhLayout.setHorizontalGroup(
            pnButtonChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        pnButtonChinhLayout.setVerticalGroup(
            pnButtonChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tb_DichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_DichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Loại dịch vụ", "Số lượng", "Giá", "Thành tiền"
            }
        ));
        tb_DichVu.setPreferredSize(new java.awt.Dimension(434, 256));
        jScrollPane1.setViewportView(tb_DichVu);
        if (tb_DichVu.getColumnModel().getColumnCount() > 0) {
            tb_DichVu.getColumnModel().getColumn(2).setResizable(false);
            tb_DichVu.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        btHuyDH.setText("HỦY HOÁ ĐƠN");
        btHuyDH.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btHuyDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHuyDHMouseClicked(evt);
            }
        });

        btXoaDV.setText("XOÁ DỊCH VỤ");
        btXoaDV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btXoaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaDVActionPerformed(evt);
            }
        });

        btThanhToan.setText("THANH TOÁN");
        btThanhToan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addComponent(btHuyDH, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnButtonChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnVoucherGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnThongTinKhach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnVoucherGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnButtonChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhachHangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btHuyDH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btXoaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        cb_LoaiDV.setMinimumSize(new java.awt.Dimension(30, 30));
        cb_LoaiDV.setPreferredSize(new java.awt.Dimension(157, 31));
        cb_LoaiDV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_LoaiDVItemStateChanged(evt);
            }
        });

        cb_DichVu.setPreferredSize(new java.awt.Dimension(30, 30));
        cb_DichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DichVuActionPerformed(evt);
            }
        });

        btn_Next.setText("Next");
        btn_Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NextMouseClicked(evt);
            }
        });

        btn_Back.setText("Back");
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(0, 153, 255));
        btn_Them.setText("Thêm");
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });

        btn_GiamSL.setBackground(new java.awt.Color(0, 153, 255));
        btn_GiamSL.setText("Giảm số lượng");
        btn_GiamSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GiamSLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnKhungTrenLayout = new javax.swing.GroupLayout(pnKhungTren);
        pnKhungTren.setLayout(pnKhungTrenLayout);
        pnKhungTrenLayout.setHorizontalGroup(
            pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhungTrenLayout.createSequentialGroup()
                .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhungTrenLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(pnKhungTrenLayout.createSequentialGroup()
                        .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhungTrenLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnKhungTrenLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cb_LoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_DichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btn_Back)
                                .addGap(38, 38, 38)
                                .addComponent(btn_Next)))
                        .addGap(11, 11, 11)))
                .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhungTrenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_GiamSL))
                    .addComponent(pnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pnKhungTrenLayout.setVerticalGroup(
            pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhungTrenLayout.createSequentialGroup()
                .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhungTrenLayout.createSequentialGroup()
                        .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cb_DichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_LoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhungTrenLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Next)
                                    .addComponent(btn_Back))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKhungTrenLayout.createSequentialGroup()
                        .addGroup(pnKhungTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_GiamSL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnDichVuLayout = new javax.swing.GroupLayout(pnDichVu);
        pnDichVu.setLayout(pnDichVuLayout);
        pnDichVuLayout.setHorizontalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        pnDichVuLayout.setVerticalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 725, Short.MAX_VALUE))
                    .addComponent(pnKhungTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnKhungTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        jMenu_QuanLy.setBackground(new java.awt.Color(0, 204, 204));
        jMenu_QuanLy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        jMenu_QuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/manager_50px.png"))); // NOI18N
        jMenu_QuanLy.setText("Quản lý");
        jMenu_QuanLy.setBorderPainted(true);
        jMenu_QuanLy.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenu_QuanLy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu_QuanLy.setIconTextGap(5);
        jMenu_QuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_QuanLyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_QuanLy);

        jMenu_ThongTinNV.setBackground(new java.awt.Color(240, 202, 90));
        jMenu_ThongTinNV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 1, true));
        jMenu_ThongTinNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/details_50px.png"))); // NOI18N
        jMenu_ThongTinNV.setText("Thông tin");
        jMenu_ThongTinNV.setBorderPainted(true);
        jMenu_ThongTinNV.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenu_ThongTinNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ThongTinNVMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_ThongTinNV);

        jMenu3.setBackground(new java.awt.Color(151, 164, 188));
        jMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout_50px.png"))); // NOI18N
        jMenu3.setText("Đăng xuất");
        jMenu3.setBorderPainted(true);
        jMenu3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String chuanHoa(String s) {
        s = s.trim();
        s = s.replaceAll("\\s+", " ");

        String a[] = s.split(" ");
        String kq = "";
        for (String x : a) {
            kq = kq + x.substring(0, 1).toUpperCase() + x.substring(1).toLowerCase();
            kq += " ";
        }
        kq = kq.trim();
        return kq;
    }

    private String layMaNV(String user) {
        String sql = "select MANV from dbo.TAIKHOAN WHERE tendangnhap='" + user + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                this.maNV = rs.getString(1);
                return this.maNV;
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("Error layMaNV()");
        }
        return "DEMO";
    }

    public void loadComboBoxLoaiDV() {

        String sql = "SELECT DISTINCT TENLOAIDV FROM LOAIDICHVU where TRANGTHAI='true'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cb_LoaiDV.addItem(rs.getString("TENLOAIDV"));
            }
            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.out.println("loadComboBoxLoaiDV()");
        }
    }

    public void loadComboBoxDichVu(String maLoaiDV) {

        String sql = "SELECT TENDV FROM DICHVU where MALOAIDV='" + maLoaiDV + "' and TRANGTHAI = 'true'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cb_DichVu.addItem(rs.getString("TENDV"));
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("loadComboBoxDichVu()");
        }
    }

    public String layMaLoaiDichVu(String loaiDV) {

        String sql = "SELECT MALOAIDV FROM dbo.LOAIDICHVU where TENLOAIDV=N'" + loaiDV + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getString("MALOAIDV");
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("layMaLoaiDichVu()");
        }
        return null;
    }

    private String layTenNV(String maNV) {

        String sql = "select TEN from dbo.NHANVIEN WHERE MANV='" + maNV + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getString(1);
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("Error kiemTraVaiTro()");
        }
        return "DEMO";
    }

    private boolean kiemTraVaiTro(String user) {

        String sql = "select vaitro from taikhoan where tendangnhap ='" + user + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String x = rs.getString("Vaitro");
                if (x.equals("1")) {
                    txt_NVDangNhap.setText(layTenNV(maNV));//
                    return true;
                } else {
                    txt_NVDangNhap.setText(layTenNV(maNV));
                    return false;
                }//
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("Error kiemTraVaiTro()");
        }
        return false;
    }

    String chuanHoaTien(String tien) {
        String t = "";
        if (tien == null) {
            return "0";
        }
        t = tien.substring(0, tien.length() - 2);
        return t;
    }
    private void rb_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_0ActionPerformed
        // TODO add your handling code here:
        txt_TongTienCK.setText("0");
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText())));
    }//GEN-LAST:event_rb_0ActionPerformed

    private void jMenu_ThongTinNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ThongTinNVMouseClicked
        // TODO add your handling code here:
        new THONGTIN(maNV).setVisible(true);
    }//GEN-LAST:event_jMenu_ThongTinNVMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LOGIN().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked
    int dau = 0;
    int cuoi = 6;

    private void cb_LoaiDVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_LoaiDVItemStateChanged
        // TODO add your handling code here:
        cb_DichVu.removeAllItems();
        loadComboBoxDichVu(layMaLoaiDichVu(cb_LoaiDV.getSelectedItem().toString()));
        btn_Back.setEnabled(false);
    }//GEN-LAST:event_cb_LoaiDVItemStateChanged
    String layMaLoaiDV(String tenLoai) {
        String s = "";
        String sql = "SELECT MALOAIDV FROM LOAIDICHVU WHERE TENLOAIDV = N'" + tenLoai + "'";

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return rs.getString(1);
            }

            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.out.println("ERR layMaLoaiDV()");
        }
        return s;
    }

    int laySoLuongDV(String maLoai) {
        int sl = 0;

        try {
            String sql1 = "SELECT COUNT(*) FROM DICHVU  WHERE MALOAIDV='" + maLoai + "' AND TRANGTHAI = 'TRUE'";
            PreparedStatement ps1 = ketNoi.prepareStatement(sql1);
            ResultSet rs1 = ps1.executeQuery();
            while (rs1.next()) {
                sl = Integer.valueOf(rs1.getString(1));
            }

            rs1.close();
            ps1.close();

        } catch (Exception e) {
            System.out.println("ERR GETSL");
        }
        return sl;
    }
    private void btn_NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NextMouseClicked
        // TODO add your handling code here:
        if (cb_DichVu.getSelectedItem() == null || cb_LoaiDV.getSelectedItem() == null) {
            btn_Next.setEnabled(false);
            return;
        }
        if (!btn_Next.isEnabled()) {
            return;
        }
        jPanel2.setVisible(false);
        jPanel2.removeAll();
        l = 0;
        int max = laySoLuongDV(layMaLoaiDV(cb_LoaiDV.getSelectedItem().toString()));
        dem = 0;
        btn_Back.setEnabled(true);
        if (max - (k + 6) <= 0) {
            btn_Next.setEnabled(false);
        } else {
            btn_Next.setEnabled(true);
        }

        jPanel2.setVisible(true);
        String sql = "SELECT MADV,TENDV,HINHANH FROM DICHVU WHERE DICHVU.MALOAIDV='" + layMaLoaiDichVu(cb_LoaiDV.getSelectedItem().toString()) + "' and trangthai = 'true' order by madv asc";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next() && l < max) {
                // LAY DON GIA

                if (l >= k) {
                    if (dem > 5) {
                        break;
                    }
                    CallableStatement c = ketNoi.prepareCall("{call loadDG(?)}");
                    c.setString(1, rs.getString(1));
                    ResultSet rs2 = c.executeQuery();
                    String tien = "";
                    if (rs2.next()) {
                        tien = rs2.getString(1).substring(0, rs2.getString(1).length() - 5);
                    }
                    //**************    
                    String path = rs.getString(3);
                    JButton btn = new JButton();

                    btn.setText("<html><body><h4>" + rs.getString(2) + "</h4><p>Giá tiền: " + tien + "</p></body></html>");
                    btn.setSize(200, 180);

                    btn.setIcon(ResizeImage(path));//"C:\\Users\\NHAT\\Desktop\\AINhandien\\Pythontest\\bbb.jpg"
                    btn.setHorizontalAlignment(SwingConstants.CENTER);
                    btn.setHorizontalTextPosition(AbstractButton.CENTER);
                    btn.setVerticalTextPosition(AbstractButton.BOTTOM);
                    jPanel2.add(btn);
                    dem++;
                }
                l++;
            }
            k = l;
            rs.close();
            ps.close();
        } catch (SQLException e) {
            System.err.println("Loi btn_NextMouseClicked");
        }
    }//GEN-LAST:event_btn_NextMouseClicked

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
        int m = 0;
        btn_Next.setEnabled(true);

        if (!btn_Back.isEnabled()) {
            return;
        }
        jPanel2.setVisible(false);
        jPanel2.removeAll();
//        dau = dau - 6;
//        cuoi = cuoi - 6;

        if ((k - dem) <= 6) {
            btn_Back.setEnabled(false);
            btn_Next.setEnabled(true);
        } else {
            btn_Back.setEnabled(true);
        }
        jPanel2.setVisible(true);
        Connection kn = KNCSDL.layKetNoi();
        String sql = "SELECT MADV,TENDV,HINHANH FROM DICHVU WHERE DICHVU.MALOAIDV='" + layMaLoaiDichVu(cb_LoaiDV.getSelectedItem().toString()) + "' and trangthai = 'true' order by madv asc";
        try {
            PreparedStatement ps = kn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                // LAY DON GIA

                if (m >= k - dem - 6 && m < k - dem) {
                    CallableStatement c = ketNoi.prepareCall("{call loadDG(?)}");
                    c.setString(1, rs.getString(1));
                    ResultSet rs2 = c.executeQuery();
                    String tien = "";
                    if (rs2.next()) {
                        tien = rs2.getString(1).substring(0, rs2.getString(1).length() - 5);
                    }
                    //**************    
                    String path = rs.getString(3);
                    JButton btn = new JButton();

                    btn.setText("<html><body><h4>" + rs.getString(2) + "</h4><p>Giá tiền: " + tien + "</p></body></html>");
                    btn.setSize(200, 180);

                    btn.setIcon(ResizeImage(path));//"C:\\Users\\NHAT\\Desktop\\AINhandien\\Pythontest\\bbb.jpg"
                    btn.setHorizontalAlignment(SwingConstants.CENTER);
                    btn.setHorizontalTextPosition(AbstractButton.CENTER);
                    btn.setVerticalTextPosition(AbstractButton.BOTTOM);
                    jPanel2.add(btn);
                }
                m++;
            }
            k = k - dem;
            dem = 6;
            rs.close();
            ps.close();
            kn.close();
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_btn_BackMouseClicked

    private void txt_TenKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TenKHKeyTyped
        // TODO add your handling code here:
//        try {
//            String s = txt_TenKH.getText();
//            s = s + evt.getKeyChar();
//            s = s.trim();
//          
//            String sql = "SELECT * FROM KHACHHANG where ten like N'%" + s + "%'";
//            PreparedStatement ps = ketNoi.prepareStatement(sql);
//            ResultSet rs = ps.executeQuery();
//
//            while (rs.next()) {
//                Vector<Object> data = new Vector<>();
//                data.add(rs.getString(1));
//                data.add(rs.getString(2));
//                data.add(rs.getString(3));
//                data.add(rs.getString(4));
//                dtm.addRow(data);
//            }
//            rs.close();
//            ps.close();
//            
//        } catch (Exception e) {
//            System.err.println("Loi txt_TenKHKeyTyped()");
//        }
    }//GEN-LAST:event_txt_TenKHKeyTyped

    private void txt_SoDTKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoDTKHKeyPressed
        // TODO add your handling code here:
        int dem = 0;
        diem = 0;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String s = txt_SoDTKH.getText();
                s = s.trim();

                String sql = "SELECT * FROM dbo.KHACHHANG WHERE SDT ='" + s + "'";
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    txt_TenKH.setText(rs.getString(3));
                    txt_DiaChiKH.setText(rs.getString(4));
                    diem = rs.getInt(5);
                    btn_ThemKH.setEnabled(false);
                    dem = 1;
                }
                rs.close();
                ps.close();

            } catch (Exception e) {
                System.err.println("Loi txt_SoDTKHKeyPressed()");
            }
            if (dem == 0) {
                JOptionPane.showMessageDialog(this, "Thông tin người dùng chưa có trong hệ thống!");
                txt_TenKH.setText("");
                txt_DiaChiKH.setText("");
                btn_ThemKH.setEnabled(true);
                rb_10.setEnabled(false);
                rb_25.setEnabled(false);
                rb_50.setEnabled(false);
            } else {
                btn_ThemKH.setEnabled(false);
            }
        }
        rb_10.setEnabled(false);
        rb_25.setEnabled(false);
        rb_50.setEnabled(false);
        if (diem >= 100) {
            rb_10.setEnabled(true);
        }
        if (diem >= 200) {
            rb_25.setEnabled(true);
        }
        if (diem >= 400) {
            rb_50.setEnabled(true);
        }
    }//GEN-LAST:event_txt_SoDTKHKeyPressed

    int laySoLuong(String bang) {
        int sl = 0;

        try {
            CallableStatement s = ketNoi.prepareCall("{call LAY_MA (?)}");
            s.setString(1, bang);
            ResultSet rs = s.executeQuery();
            while (rs.next()) {
                sl = rs.getInt(1);
            }
            rs.close();

        } catch (Exception e) {
            System.out.println("ERR GETSL");
        }
        return sl;
    }

    boolean checkFillKH(String sdt) {
        if (txt_SoDTKH.getText().equals("")) {
            return false;
        }
        if (txt_TenKH.getText().equals("")) {
            return false;
        }
        return true;
    }

    private boolean checkTT_SDTKH(String sdt) {
        try {
            sdt = sdt.trim();

            String sql = "SELECT * FROM dbo.KHACHHANG WHERE sdt='" + sdt + "'";
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                maKH = rs.getString(1);
                return true;
            }
            rs.close();
            ps.close();

        } catch (Exception e) {
            System.err.println("Loi checkTT_SDTKH()");
        }
        return false;
    }

    boolean checkSDT(String sdt) {
        String pSDT = "0[0-9]{9}";
        if (!sdt.matches(pSDT)) {
            return false;
        }
        return true;
    }
    private void btn_ThemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemKHMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (!btn_ThemKH.isEnabled()) {
            return;
        }

        if (checkFillKH(txt_SoDTKH.getText().trim())) {
            if (!checkSDT(txt_SoDTKH.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!");
                return;
            }
            if (checkTT_SDTKH(txt_SoDTKH.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại!");
                return;
            }
            int sl = laySoLuong("KHACHHANG");
            String sql = "insert into KHACHHANG values (?,?,?,?,?)";
            try {
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, "KH" + (sl + 1));
                ps.setString(2, txt_SoDTKH.getText());
                ps.setString(3, chuanHoa(txt_TenKH.getText()));
                ps.setString(4, txt_DiaChiKH.getText());
                ps.setInt(5, 0);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
                btn_ThemKH.setEnabled(false);
                ps.close();

            } catch (Exception ex) {
                System.out.println("ERR ThemKH()");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn cần nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btn_ThemKHMouseClicked

    String layMaDV(String tenDV, String maLoaiDV) {
        String sql = "SELECT MADV FROM DICHVU WHERE TENDV=N'" + tenDV + "' AND MALOAIDV='" + maLoaiDV + "'";

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getString(1);
            }
            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.out.println("ERR layMaLoaiDV()");
        }
        return null;
    }


    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked
        // TODO add your handling code here:
        if (cb_DichVu.getSelectedItem() == null || cb_LoaiDV.getSelectedItem() == null) {
            return;
        }
        dtm = (DefaultTableModel) tb_DichVu.getModel();

        String dv = cb_DichVu.getSelectedItem().toString();
        String loaiDV = cb_LoaiDV.getSelectedItem().toString();
        Vector<Object> data = new Vector<>();
        data.add(dv);
        data.add(loaiDV);
        // XU LY LAY SO LUONG
        int sl = 1;
        int row = dtm.getRowCount();
        if (row > 0) {
            for (int i = 0; i < row; i++) {
                int j = tb_DichVu.getSelectedRow();
                if (layMaDV(dtm.getValueAt(i, 0).toString(), layMaLoaiDV(dtm.getValueAt(i, 1).toString()))
                        .equals(layMaDV(dv, layMaLoaiDV(loaiDV)))) {
                    sl = sl + Integer.valueOf(dtm.getValueAt(i, 2).toString());
                    dtm.setValueAt(sl, i, 2);
                    dtm.setValueAt(Long.valueOf(dtm.getValueAt(i, 3).toString()) * sl, i, 4);
                    long tongTien = 0;
                    for (int k = 0; k < row; k++) {
                        tongTien += Long.valueOf(dtm.getValueAt(k, 4).toString());
                    }
                    txt_TongTien.setText(String.valueOf(tongTien));
                    if (rb_0.isSelected()) {
                        rb_0ActionPerformed(null);
                    } else if (rb_10.isSelected()) {
                        rb_10ActionPerformed(null);
                    } else if (rb_25.isSelected()) {
                        rb_25ActionPerformed(null);
                    } else if (rb_50.isSelected()) {
                        rb_50ActionPerformed(null);
                    }
                    txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
                    return;
                }
            }
        }

        data.add(sl);

        // XU LY LAY DON GIA
        Connection ketNoi = KNCSDL.layKetNoi();
        String tmp = "";
        try {
            CallableStatement c = ketNoi.prepareCall("{call loadDG(?)}");
            c.setString(1, layMaDV(cb_DichVu.getSelectedItem().toString(), layMaLoaiDV(cb_LoaiDV.getSelectedItem().toString())));
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//            String ngay = sdf.format(dateChooserCombo1.getSelectedDate().getTime());
//            c.setString(2, ngay);
            ResultSet rs2 = c.executeQuery();
            if (rs2.next()) {
                tmp = rs2.getString(1).substring(0, rs2.getString(1).length() - 5);
            }
            rs2.close();
            c.close();

        } catch (SQLException ex) {

        }
        Long tien = Long.valueOf(tmp);
        data.add(tien);
        data.add(tien * sl);
        dtm.addRow(data);

        // XU LY TIEN THANH TOAN
        long tongTien = 0;
        row = dtm.getRowCount();
        if (row > 0) {
            for (int i = 0; i < row; i++) {
                tongTien += Long.valueOf(dtm.getValueAt(i, 4).toString());
            }
        }
        txt_TongTien.setText(String.valueOf(tongTien));
        if (rb_0.isSelected()) {
            rb_0ActionPerformed(null);
        } else if (rb_10.isSelected()) {
            rb_10ActionPerformed(null);
        } else if (rb_25.isSelected()) {
            rb_25ActionPerformed(null);
        } else if (rb_50.isSelected()) {
            rb_50ActionPerformed(null);
        }
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
    }//GEN-LAST:event_btn_ThemMouseClicked

    private void rb_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_10ActionPerformed
        // TODO add your handling code here:
        Long tmp = Long.valueOf(txt_TongTien.getText());
        txt_TongTienCK.setText(chuanHoaTien(String.valueOf(tmp * 0.1)));
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
    }//GEN-LAST:event_rb_10ActionPerformed

    private void rb_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_25ActionPerformed
        // TODO add your handling code here:
        Long tmp = Long.valueOf(txt_TongTien.getText());
        txt_TongTienCK.setText(chuanHoaTien(String.valueOf(tmp * 0.25)));
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
    }//GEN-LAST:event_rb_25ActionPerformed

    private void rb_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_50ActionPerformed
        // TODO add your handling code here:
        Long tmp = Long.valueOf(txt_TongTien.getText());
        txt_TongTienCK.setText(chuanHoaTien(String.valueOf(tmp * 0.50)));
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
    }//GEN-LAST:event_rb_50ActionPerformed

    private void txt_TongTienTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TongTienTTMouseClicked
        // TODO add your handling code here:
        Long tmp = Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText());
        txt_TongTienTT.setText(String.valueOf(tmp));
    }//GEN-LAST:event_txt_TongTienTTMouseClicked
    void xoaTrang() {
        rb_0.setSelected(true);
        txt_SoDTKH.setText("");
        txt_TenKH.setText("");
        txt_DiaChiKH.setText("");
        txt_TongTien.setText("");
        txt_TongTienCK.setText("0");
        txt_TongTienTT.setText("");
        rb_10.setEnabled(false);
        rb_25.setEnabled(false);
        rb_50.setEnabled(false);
    }
    private void btHuyDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHuyDHMouseClicked
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn huỷ hoá đơn hay không", "Xác nhận huỷ hoá đơn", 0);
        if (x == JOptionPane.YES_OPTION) {
            dtm = (DefaultTableModel) tb_DichVu.getModel();
            dtm.setRowCount(0);
            xoaTrang();
            JOptionPane.showMessageDialog(this, "Huỷ hoá đơn thành công!");
        }
    }//GEN-LAST:event_btHuyDHMouseClicked

    private void btXoaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaDVActionPerformed
        // TODO add your handling code here:

        dtm = (DefaultTableModel) tb_DichVu.getModel();
        if (dtm.getRowCount() == 0 || tb_DichVu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Không có gì để xoá");
            return;
        }
        int i = tb_DichVu.getSelectedRow();
        dtm.removeRow(i);
//         xoaTrang();
        tinhTien();
    }//GEN-LAST:event_btXoaDVActionPerformed
    void tinhTien() {
        long tongTien = 0;
        int row = dtm.getRowCount();
        if (row > 0) {
            for (int k = 0; k < row; k++) {
                tongTien += Long.valueOf(dtm.getValueAt(k, 4).toString());
            }
        }
        txt_TongTien.setText(String.valueOf(tongTien));

        if (rb_0.isSelected()) {
            rb_0ActionPerformed(null);
        } else if (rb_10.isSelected()) {
            rb_10ActionPerformed(null);
        } else if (rb_25.isSelected()) {
            rb_25ActionPerformed(null);
        } else if (rb_50.isSelected()) {
            rb_50ActionPerformed(null);
        }
        txt_TongTienTT.setText(String.valueOf(Long.valueOf(txt_TongTien.getText()) - Long.valueOf(txt_TongTienCK.getText())));
    }
    private void btn_GiamSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GiamSLActionPerformed
        // TODO add your handling code here: 
        dtm = (DefaultTableModel) tb_DichVu.getModel();
        if (dtm.getRowCount() == 0 || tb_DichVu.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dịch vụ");
            return;
        }
        int i = tb_DichVu.getSelectedRow();
        int sl = Integer.valueOf(dtm.getValueAt(i, 2).toString());
        if (sl - 1 == 0) {
            dtm.removeRow(i);
        } else {
            sl--;
            dtm.setValueAt(sl, i, 2);
            dtm.setValueAt(Long.valueOf(dtm.getValueAt(i, 3).toString()) * sl, i, 4);
        }
        tinhTien();
    }//GEN-LAST:event_btn_GiamSLActionPerformed

    void cap_Nhat_Diem_Tich_Luy(String sDT, int diem) {
        String sql = "update KHACHHANG set DIEMTICHLUY = ? where SDT = ?";

        try {
            PreparedStatement p = ketNoi.prepareStatement(sql);
            p.setInt(1, diem);
            p.setString(2, sDT);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Loi cap_Nhat_Diem_Tich_Luy()");
        }

    }

    private void btThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThanhToanActionPerformed
        // TODO add your handling code here:
        dtm = (DefaultTableModel) tb_DichVu.getModel();
        if (dtm.getRowCount() > 0) {

            if (checkFillKH(txt_SoDTKH.getText().trim())) {
                if (!checkSDT(txt_SoDTKH.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!");
                    return;
                }
                if (!checkTT_SDTKH(txt_SoDTKH.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Thông tin khách hàng chưa có trong cơ sở dữ liệu, cần thêm mới khách hàng");
                    return;
                }
                int x = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn thanh toán hay không", "Xác nhận xoá tài khoản", 0);
                if (x == JOptionPane.YES_OPTION) {
                    // XU LY THEM HOA DON
                    int sl = laySoLuong("HOADON") + 1;
                    String maHD = "HD" + sl;
                    String sql = "insert into HOADON values (?,?,?,?,?,?)";
                    // mahd, ngaylap, sdt ,chietkhau,tongtien,manv

                    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                    try {
                        PreparedStatement ps = ketNoi.prepareStatement(sql);
                        ps.setString(1, maHD);
                        ps.setTimestamp(2, timestamp);
                        ps.setString(3, maKH);

                        if (rb_0.isSelected()) {
                            ps.setInt(4, 0);
                        } else if (rb_10.isSelected()) {
                            ps.setInt(4, 10);
                            cap_Nhat_Diem_Tich_Luy(txt_SoDTKH.getText(), diem -= 100);
                        } else if (rb_25.isSelected()) {
                            ps.setInt(4, 25);
                            cap_Nhat_Diem_Tich_Luy(txt_SoDTKH.getText(), diem -= 200);
                        } else if (rb_50.isSelected()) {
                            ps.setInt(4, 50);
                            cap_Nhat_Diem_Tich_Luy(txt_SoDTKH.getText(), diem -= 400);
                        }
                        ps.setLong(5, Long.valueOf(txt_TongTienTT.getText()));
                        ps.setString(6, maNV);
                        ps.executeUpdate();
                        cap_Nhat_Diem_Tich_Luy(txt_SoDTKH.getText(), diem + Integer.valueOf(txt_TongTienTT.getText()) / 1000);
                        xoaTrang();
                        JOptionPane.showMessageDialog(this, "Thêm hoá đơn mới thành công!");
                        ps.close();

                    } catch (Exception e) {
                        System.err.println("Loi them Hoa Don");
                    }

                    // XU LY CT HOA DON
                    String sql1 = "insert into CT_HOADON values (?,?,?)";
                    // mahd,madv,soluong
                    String maDV = "";
                    int row = dtm.getRowCount();
                    for (int i = 0; i < row; i++) {
                        maDV = layMaDV(dtm.getValueAt(i, 0).toString(), layMaLoaiDV(dtm.getValueAt(i, 1).toString()));
                        try {
                            PreparedStatement ps1 = ketNoi.prepareStatement(sql1);
                            ps1.setString(1, maHD);
                            ps1.setString(2, maDV);
                            ps1.setInt(3, Integer.valueOf(dtm.getValueAt(i, 2).toString()));
                            ps1.executeUpdate();
                        } catch (Exception e) {
                            System.err.println("Loi them CTHoa Don");
                        }
                    }
                    dtm.setRowCount(0);
                } 
//                else {
//                    JOptionPane.showMessageDialog(this, "Bạn cần nhập đầy đủ thông tin khách hàng");
//                }
            } else {
                JOptionPane.showMessageDialog(this, "Thông tin khách hàng chưa đầy đủ!");
            }
        }else {
                JOptionPane.showMessageDialog(this, "Chưa có gì để thanh toán!");
            }
    }//GEN-LAST:event_btThanhToanActionPerformed

    private void jMenu_QuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_QuanLyMouseClicked
        // TODO add your handling code here:
        new ADMIN().setVisible(true);
    }//GEN-LAST:event_jMenu_QuanLyMouseClicked

    private void txt_SoDTKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoDTKHKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyCode() != KeyEvent.VK_ENTER) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_SoDTKHKeyTyped

    private void cb_DichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DichVuActionPerformed
        // TODO add your handling code here:
        String maLoaiDV = layMaLoaiDichVu(cb_LoaiDV.getSelectedItem().toString());
        if (cb_DichVu.getSelectedItem() == null) {
            return;
        }
        String tenDV = cb_DichVu.getSelectedItem().toString();
        String maDV = layMaDV(tenDV, maLoaiDV);
        k = 0;
        btn_Back.setEnabled(false);
        int max = laySoLuongDV(layMaLoaiDichVu(cb_LoaiDV.getSelectedItem().toString()));
        if (max - 6 <= 0) {
            btn_Next.setEnabled(false);
        } else {
            btn_Next.setEnabled(true);
        }
        jPanel2.setVisible(false);
        jPanel2.removeAll();
        jPanel2.setVisible(true);
        String sql = " SELECT MADV,TENDV,HINHANH FROM DICHVU WHERE MADV = ?";
        String sql2 = "SELECT MADV,TENDV,HINHANH FROM DICHVU WHERE DICHVU.MALOAIDV=? and MADV!=? and trangthai = 'true' ";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, maDV);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                //LAY DON GIA
                CallableStatement c = ketNoi.prepareCall("{call loadDG(?)}");
                c.setString(1, rs.getString(1));
                ResultSet rs2 = c.executeQuery();
                String tien = "";
                if (rs2.next()) {
                    tien = rs2.getString(1).substring(0, rs2.getString(1).length() - 5);
                }
                //**************    
                String path = rs.getString(3);
                JButton btn = new JButton();

                btn.setText("<html><body><h4>" + rs.getString(2) + "</h4><p>Gía tiền: " + tien + "</p></body></html>");
                rs2.close();
                c.close();
                btn.setSize(200, 180);
                btn.setIcon(ResizeImage(path));
                btn.setHorizontalAlignment(SwingConstants.CENTER);
                btn.setHorizontalTextPosition(AbstractButton.CENTER);
                btn.setVerticalTextPosition(AbstractButton.BOTTOM);
                jPanel2.add(btn);
                k++;
            }
            ps = ketNoi.prepareStatement(sql2);
            ps.setString(1, maLoaiDV);
            ps.setString(2, maDV);
            rs = ps.executeQuery();
            while (rs.next()) {
                //LAY DON GIA
                CallableStatement c = ketNoi.prepareCall("{call loadDG(?)}");
                c.setString(1, rs.getString(1));
                ResultSet rs2 = c.executeQuery();
                String tien = "";
                if (rs2.next()) {
                    tien = rs2.getString(1).substring(0, rs2.getString(1).length() - 5);
                }
                //**************    
                String path = rs.getString(3);
                JButton btn = new JButton();

                btn.setText("<html><body><h4>" + rs.getString(2) + "</h4><p>Gía tiền: " + tien + "</p></body></html>");
                rs2.close();
                c.close();
                btn.setSize(200, 180);
                btn.setIcon(ResizeImage(path));
                btn.setHorizontalAlignment(SwingConstants.CENTER);
                btn.setHorizontalTextPosition(AbstractButton.CENTER);
                btn.setVerticalTextPosition(AbstractButton.BOTTOM);
                jPanel2.add(btn);
                k++;
                if (k == 6) {
                    break;
                }
            }
            rs.close();
            ps.close();
        } catch (SQLException e) {
        }
//        
    }//GEN-LAST:event_cb_DichVuActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANTRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANTRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANTRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANTRI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new QUANTRI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuyDH;
    private javax.swing.JButton btThanhToan;
    private javax.swing.JButton btXoaDV;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_GiamSL;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_DichVu;
    private javax.swing.JComboBox<String> cb_LoaiDV;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_QuanLy;
    private javax.swing.JMenu jMenu_ThongTinNV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiaChiKhachHang;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbSoDTKhachHang;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JLabel lbTongToen;
    private javax.swing.JLabel lbTongToen1;
    private javax.swing.JLabel lbTongToen2;
    private javax.swing.JLabel lbVoucher;
    private javax.swing.JPanel pnButtonChinh;
    private javax.swing.JPanel pnDichVu;
    private javax.swing.JPanel pnGroupButton;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnKhungTren;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnThongTinKhach;
    private javax.swing.JPanel pnVoucherGroup;
    private javax.swing.JRadioButton rb_0;
    private javax.swing.JRadioButton rb_10;
    private javax.swing.JRadioButton rb_25;
    private javax.swing.JRadioButton rb_50;
    private javax.swing.JTable tb_DichVu;
    private javax.swing.JTextField txt_DiaChiKH;
    private javax.swing.JLabel txt_NVDangNhap;
    private javax.swing.JTextField txt_SoDTKH;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TongTien;
    private javax.swing.JTextField txt_TongTienCK;
    private javax.swing.JTextField txt_TongTienTT;
    // End of variables declaration//GEN-END:variables
}
